export default {
  /***** Fetch Todo *****/
  FETCH_TODOS_LOADING: "FETCH_TODOS_LOADING",
  FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
  FETCH_TODOS_FAILURE: "FETCH_TODOS_FAILURE",

  /***** Add Todo *****/
  ADD_TODOS_SUCCESS: "ADD_TODOS_SUCCESS",
  ADD_TODOS_FAILURE: "ADD_TODOS_FAILURE",

  /***** Update Todo *****/
  UPDATE_TODOS_SUCCESS: "UPDATE_TODOS_SUCCESS",
  UPDATE_TODOS_FAILURE: "UPDATE_TODOS_FAILURE",

  /***** Fetch Current User *****/
  FETCH_CURRENT_USER_SUCCESS: "FETCH_CURRENT_USER_SUCCESS",
  FETCH_CURRENT_USER_ERROR: "FETCH_CURRENT_USER_ERROR",

  /***** Fetch All Users *****/
  FETCH_ALL_USERS_LOADING: "FETCH_ALL_USERS_LOADING",
  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_ERROR: "FETCH_ALL_USERS"
};
