export default {
  /***** Fetch Todo *****/
  FETCH_TODOS_LOADING: "FETCH_TODOS_LOADING",
  FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
  FETCH_TODOS_FAILURE: "FETCH_TODOS_FAILURE",

  /***** Add Todo *****/
  ADD_TODOS_LOADING: "ADD_TODOS_LOADING",
  ADD_TODOS_SUCCESS: "ADD_TODOS_SUCCESS",
  ADD_TODOS_FAILURE: "ADD_TODOS_FAILURE",

  /***** Update Todo *****/
  UPDATE_TODOS_SUCCESS: "UPDATE_TODOS_SUCCESS",
  UPDATE_TODOS_FAILURE: "UPDATE_TODOS_FAILURE"
};